import jonJoeyPic from './candidate-pics/JonJoeyTelebrico.jpg';
import joshnagra from './candidate-pics/joshnagra.jpg';
import colinsam from './candidate-pics/colinsam.jpeg';
import zane from './candidate-pics/zaneyamamoto.JPG';
import kirbykimball from './candidate-pics/kirbykimball.jpg';
import sambogen from './candidate-pics/sambogen.JPG';
import sophiedvorkin from './candidate-pics/sophiedvorkin.jpeg';
import amarihuang from './candidate-pics/amarihuang.jpeg';
import cristianpang from './candidate-pics/cristianpang.jpg';
import gio from './candidate-pics/giovannipierre.jpeg';
import bryan from './candidate-pics/bryansoh.jpg'
import blank from './candidate-pics/blank.jpg'
import ian from './candidate-pics/ianblaime.jpeg'
import wolfy from './candidate-pics/wolfy.png'
import chris from './candidate-pics/chris.png'
import maya from './candidate-pics/mayakurkhill.jpg'
import concp from './candidate-pics/con-cp.png'
import addy from './candidate-pics/addison.PNG'
import bianca from './candidate-pics/bianca.jpg'

// import ascmcLogo from './candidate_info/candidate-pics/ascmclogo.jpg';
// import ascmcLogo from './candidate_info/candidate-pics/ascmclogo.jpg';

export const president_candidate_data = [
    {
      imageSource: joshnagra,
      name: 'Josh Nagra (President)',
      candidateDescription: ['Hello CMC!', 'My name is Josh Nagra, and it has been a pleasure serving as the Presidential Advisor for Mental Health and Wellness. As a queer student of color, I hope you find my experience and platform worthy of being your ASCMC President :) #MoshWithJosh', 'Other than bringing Megan Thee Stallion to Mckennapalooza and having more than one-ply toilet paper, I am dedicated to the following issues:', 'Supporting students of marginalized identities', '1) Guaranteed increases in funding for affinity groups. 2) Allocating dorm budgets for free menstrual products and laundry detergent pods. 3) Exempt all affinity groups from any limitations on spending during budget freeze. 4) Work with Roberts Pavilion to eliminate PE course fees. 5) Creating a comprehensive list of financial resources for students on campus', 'Mental health/Physical Wellbeing', '1) Free ‘Question, Persuade, Refer’ and Teal Dot training for all students offered year-round. 2) Start a peer-to-peer emotional health service providing relevant mental health support. 3) Provide generic Plan-B to all RAs in addition to contraceptives', 'Ensuring responses to every email and question for ASCMC officers', '1) Frequent accountability check-ins with every ASCMC officer', 'Student-Athletes', '1) Encouraging game attendance through kickbacks before and after events. 2) Snack bars and nutrition in training rooms', 'Inclusive and enjoyable ASCMC parties', '1) Direct feedback on ASCMC planned parties. 2) STOP TURNING ON THE SPRINKLERS ON GREEN BEACH DURING PARTIES. 3) Pay Advocates who lifeguard parties for their service to community safety', 'Supporting international students', '1) Streamlined documents and guides for filing taxes, renewing visas, and adjusting to a novel culture. 2) Hiring a drop-in therapist for international students. 3) Pressuring DOS to provide resources for students transitioning back to campus', 'In addition to:', '1) Ending ASCMC Closed-doors. 2) Unapologetically speaking up for students in faculty and trustee meetings. 3) Ending lack of ASCMC access for FGLI-students. 4) Supporting differently-abled students, faculty, and staff. 5) Increasing clarity regarding COVID-19'],
    },

    {
      imageSource: jonJoeyPic,
      name: 'Jon Joey Telebrico (President)',
      candidateDescription: ['Hello, CMC! I am Jon Joey “JJ” Telebrico (he/they), a low-income student, affinity group leader, and committed ally. I hope to bring a fresh perspective to ASCMC as your next President! I have worked tirelessly to improve CMC through ASCMC. This past year, I have served as ASCMC’s Vice President of Campus Organizations, redistributing thousands of dollars to student organizations— including affinity groups—and promoting CMC’s vibrant extracurricular life.', 'You can read about my past contributions, present work, and future vision (including 17 pages of policy solutions!) at linktr.ee/jj4ascmcpres or on Instagram @jj4ascmcpres', 'Below is my three-pronged platform:', 'Communal Support: Funding for affinity organizations. International student resources. CMS athlete tailgates. Culturally-adapted mental health support. Free menstrual products and washing/drying. First-year room retention. Platforms for marginalized students. When we show up for one another, we can create an experience that is accessible, inclusive, and welcoming for all. Community is at the heart of CMC—through robust policy changes and extensive events programming, I pledge to make CMC a place that uplifts every student in our community.', 'Institutional Transparency: As the student body representative, I vow to hold CMC administrators responsible for timely and effective communication. It is critical that administrators provide policy updates and guidelines on social gatherings, anti-racism efforts, and campus safety so that students are aware of the changes that impact them.', 'Student Advocacy: Proactive engagement with campus organizations. Steadfast commitments to marginalized students. Consistent empowerment of the wider student body. CMCers have the power to enact meaningful change—ASCMC must address student concerns through dialogue and action, supporting the student body as active advocates in the affairs that affect them. Following long periods of disconnection, ASCMC is at a unique spot where it can redefine our culture to meaningfully involve everyone. Let’s connect, and build this community—together.'
      
    ]
    },

    {
      imageSource: colinsam,
      name: 'Colin Sam (President)',
      candidateDescription: ['Hey CMC!', 'I’m Colin (he/him/his) and I’m from the greatest city in the world: Cincinnati, but both of my parents were born and raised in Monrovia, Liberia. I’m a big Bengals, Lakers, Ohio State, Real Madrid, and Chelsea fan; I love playing video games, sports, and doing volunteer work.','Before coming to CMC, I went to Cincinnati Country Day School for 12 years and participated in our student government as the school’s first Black student body president. At CMC, I was the Freshman and Sophomore class president for the class of 2023, co-founded CMC Volunteer Club, and I work at Roberts.', 'There are four main reasons why I should be the next ASCMC President: I love this school, I know our students, I have the experience, and I will be committed to the job.', 'First and foremost, I genuinely LOVE this school. Being here I have made so many lifelong friends; students, faculty, and staff. Most importantly, this is a place where I feel truly accepted and loved and that’s an experience we all deserve.','I KNOW the students here. I am an outgoing person and every day I meet new people who give me a new perspective on our campus. I love talking to as many people as I can and try to always be approachable.', 'I have the EXPERIENCE in ASCMC with two years as a class president and one year running an ASCMC club. Throughout my time in ASCMC, I’ve seen what works and more importantly what does not, so I have plenty of ideas about improving the organization.', 'Lastly, I am COMMITTED to the job of President. Being ASCMC President comes with a lot of responsibilities and it’s important that our President can commit their time fully to the needs of our student body.'],
    },
    {
      imageSource: maya,
      name: 'Maya Kurkhill (President)',
      candidateDescription: ['IG: maya.ascmc.pres', 'Hey! I’m Maya Kurkhill (she/her/hers); and I’m so excited to bring all of our perspectives into ASCMC and enact long-term, institutional reforms. You can count on me to go beyond DL-emails and talk with you about your life at CMC. You might have even spoken with me at the Athenaeum or outside of the Hub about what you would like to see in this community :-)', 'From our conversations, there are a few things that I will highlight (although there are many more… including amazing food/Collins + caffeine driven policies):', 'Long-lasting change that supports affinity group leaders and student organizations such as digitizing funding request process to ASCMC’s nearly $500k budget and  (WOW)','Structural resources for international students, LGBTQ+ students, transfers, and students with accommodations/disabilities:', '1) Travel funding, robust programming, and office for international students', '2) Gender inclusive housing and bathrooms', '3) Investigation into Accommodations Office', '4) Comprehensive orientation for transfer students', '', 'Improving mental and physical health – more and timely therapy, facing pressures such as w/ pre-professional groups on-campus, providing sexual health resources in the dorms', 'Rebuilding community cohesion through varied and diverse events/parties for all years to enjoy themselves! Let’s invite LA artists/DJs, have intercultural festivals, etc. ', 'As a woman of color, I have learned how to advocate for myself and the communities around me. Coming to CMC as a 5C transfer + immunocompromised/neurodivergent student during the pandemic, I experienced extraordinary support. I also experienced what it is like to fall through the cracks and face heavy opposition to equal access.', 'That is why I have directly negotiated and succeeded in removing barriers at the Claremont Colleges for all students even in my first semester transferring. Among other things, I worked directly with DOS to create safer policies for immunocompromised students; and I oversaw the creation of PZ’s Bachelor’s degree program for incarcerated students.', 'Ultimately, I am committed to speaking up for long-term change in ASCMC. Our platforms for inclusivity and equity need to outlast my time as President. I love that we can dedicate funding to affinity groups and student organizations this year, but we need that process to be transparent and dependable every year. And let’s have a good time while doing it!'] },
]

export const evp_candidate_data = [
    {
      imageSource: zane,
      name: 'Zane Yamamoto (EVP)',
      candidateDescription: ['Hey CMC!', 'My name is Zane Yamamoto and I\’m running to be your Executive Vice President! I was born and raised in Honolulu, Hawaii and I\’m currently the Sophomore Class President. Last year, I served as a senator on the AAA committee after a less-than-successful run for first-year class president. I have built working relationships within ASCMC and an intimate knowledge of how to navigate the bureaucracy of the Senate and Executive Board in order to get things done.', 'As EVP, I will work to bring more people to the Senate and have the agenda reflect the everyday concerns of students. Modeling both the legendary Cindy Lay and Sam Harrison, Senate will feature Deep Dives into campus issues, senator-led initiatives, and Town Halls with important guests. The Senate should be at the forefront of tackling challenges facing CMC students, especially marginalized students.', 'A CMC that isn’t right for some of us is a CMC that doesn’t work for all of us.', '', 'I\’m running to unlock the potential of ASCMC even if it doesn\’t always play out in practice.', 'I\’m running because a 400K budget can produce tangible impact.', 'I’m running for an ASCMC that works.','','I’m running to: ', 'Define our “New Normal.” ASCMC should proactively work with the administration to define the ‘new normal’ for campus. The Senate should elevate student voices in this discussion and make admin decisions transparent.', 'Focus on Students. (and Services!) We should concentrate on how ASCMC can meet the needs and concerns of students. The Senate should serve as a conduit for identifying those needs and creating solutions.', 'Transform ASCMC. The “Corporation” needs more than facelifts or floor speeches. I will continue the work of the Organizational Review Committee in examining, analyzing, and solving ASCMC’s problems.', 'Aloha & Live Long and Prosper','-Zane #VoteZ4EVP'],
    },

]

export const vpsa_candidate_data = [
    {
      imageSource: chris,
      name: 'Christopher LaRovere (VPSA)',
      candidateDescription: ['Yay! :)'],
    },
]

export const dac_candidate_data = [
  {
    imageSource: kirbykimball,
    name: 'Kirby Kimball (DAC)',
    candidateDescription: ['As the 2022-2023 ASCMC Dormitory Affairs Chair (DAC), I aim to translate campus desires and frustrations to the administrative world of CMC: a connection that is much needed after our return to campus post-pandemic lockdown. I have the requisite leadership skills and work-ethic to take social life – its successes and failures – and institute concrete change. Celebration and support must return after the incredibly taxing two years we’ve experienced as young adults. As Community Service Interim Chair for ASCMC during my freshman fall term, my goal was to tackle local and national needs by engaging the CMC student body. From experiential service trips with local NPOs to social fundraising events, my time serving ASCMC and the greater Pomona Valley community has made a mark. I would be grateful to continue this impact in an Executive Board position as your DAC. Highly involved in multiple facets of the CMC community, I have made impactful social connections with students of many interest groups. My desire to be your DAC stems from the conversations I’ve had with these diverse groups of students: there is a lack of community across quads/dorms and there needs to be more administrative support to our CMCers, especially after the world-altering effects of the pandemic. Free bonding adventures with intersecting quads, mandatory supply of menstrual products, dorm service trips, mental health support and general SHS improvement, and regular cultural celebrations are all ideas I plan to make a reality, ideas I’ve gathered from you: my peers. In an effort to remain accessible and open to change, I will host weekly office hours and work on-call with DOS/RAs to address pressing campus-life problems. Fixing road bumps along the way, as DAC I’ll ensure that you’ll recall the 2022-2023 CMC term 40 years from now as truly “the good life”.'],
  },
]

// // 2023
export const senior_candidate_data = [
    {
      imageSource: sambogen,
      name: 'Sam Bogen (2023 President)',
      candidateDescription: ['Hey everyone! My name is Sam Bogen, and I am running to be your Senior Class President. I am ASCMC’s current Academic Affairs Chair, and I also help the Events team plan parties like Monte Carlo, Wedding Party, and Mistletoe Rock.', 'It’s crazy to think that we will be Seniors next year. It seems like yesterday that we were moving out in March 2020. Little did we know then that it would be 18 months before we were reunited on campus. As your Senior Class President, I plan on making up for that lost time.', 'In the interim, we have seen our class grow with new transfer students and students who took LOAs. That 18 months was even longer for folks who studied abroad this past fall, and there are over 40 students studying abroad right now. All of this means we need a Senior Class President who will bring this class together by making every member feel supported. That is why Support is the first part of my SENIOR (Support, Events, New Ideas, Inclusion, Opportunity, Resources) initiative. I want to celebrate all of us as we go into senior year, whether that is through mental health programming, awesome parties, pre-games, study breaks, and takeovers. No matter what, we all have something worth celebrating, and I hope to celebrate all of you next year.', 'If elected, I hope to not only bring my ideas to the table but yours too. I will work diligently to select a diverse cabinet, build upon existing senior traditions and create new ones, plan the best parties, and make sure that every one of us feels supported.', 'While you’re here, please check out my campaign Insta @SamBfor2023 for more information on my platform, initiatives, and ideas. Vote Sam B for 2023!', ' ', ' '],
    },

    {
      imageSource: sophiedvorkin,
      name: 'Sophie Dvorkin (2023 President)',
      candidateDescription: ['Hello CMC Class of 2023!', 'My name is Sophie Dvorkin and I’m running to be your Senior Class President. I believe my plans for our Senior Year speak louder than I do in most instances (that’s pretty damn loud). Since our first year, our class has gone through a lot of change - from a year and a half of online school to some of us moving to AK to new students joining us from other classes and other schools.', 'Our class deserves an incredible Senior Year where we continue to bond as a class and celebrate how far we’ve come since our first year. As Senior Class President, I know I will get the job done. Here are some of the ideas I’d like to implement on campus:', '1) Casual and consistent events like painting workshops, Wine Wednesdays, and cocktail/mocktail classes twice a month will help us stay in touch and destress from our weeks, in addition to better-than-ever hallmark events like 200/100 Days, Thesis Parties, and Las Vegas.', '2) Post-grad resources catered to your needs. By collaborating with the Soll Center, we will set up workshops for resumes and cover letters specifically for full-time opportunities, as well as grad school applications so that we’re prepared to leave the Claremont nest.', '3) An Alumni Liaison on Class Cabinet will help facilitate low-stakes conversations with alumni to make connections and hear more about their career paths.', '4) Events that support our senior athletes: tailgates with fun games and activities, promotion of Senior Nights and key games to show our CMS spirit through an Athletics Liaison, and interactive half-time action so that there’s never a dull moment.', 'Above all, as Senior Class President, I want to hear your thoughts and do what I can to make the most out of our Senior Year. I promise to be accessible, receptive, and creative with our time and money.', 'CMC 2023: We’ve come so far. Let’s make our last one our best one.', ' ', ' '],
    },

    {
      imageSource: amarihuang,
      name: 'Amari Huang (2023 President)',
      candidateDescription: ['Hi everyone! My name is Amari Huang (first name pronounced “Emory” like the university) and I am running for Senior Class President! I am currently your Junior Class President, and I would be honored to serve as your class president again.', 'I have had the joy of getting to know a lot of you over the last three years whether that was through the Athenaeum, classes, the Keck Center for International and Strategic Studies, on-campus events, or currently as your class president. I feel privileged to have met all of you and to feel at home with various communities at CMC', 'If elected, I will bring forth my own experiences and new ideas, and bring together a diverse group of members of our class for our senior class cabinet. I also look forward to supporting my goals in these ways:', 'Memorable Activities:', '1) Continuing and improving senior year classics including 200 and 100 days and senior thesis party. 2) Organizing senior class pregames with drinks, food, and music. 3) Creating varying events to include your interests or interests you never knew you had!', 'Diversity and Inclusion:', '1) Including cabinet members with different perspectives and varying tastes. 2) Integrating all members of our class, including those who took gap semester(s) and those who are currently abroad. 3) Finding a passionate and dedicated commencement speaker - Creating various alumni panels for multiple career paths', 'Mental Health:', '1) Recognizing that while senior year is a lot of fun, thesis and job-search can also be stressful. 2) Continuing with morning snacks like coffee, pie, acai smoothies etc. 3) Collaborating with CPB and other groups on campus. 4) Sharing mental health resources in every email, and working with the elected president to make resources more available. 5) Listening to YOUR needs', 'For more information, please check out my Instagram @amari.2023',],
    },
]

// // 2024
export const junior_candidate_data = [
    {
      imageSource: concp,
      name: 'Cristian Pang (2024 President)',
      candidateDescription: ['Hello everyone! For those who don’t know me my name is Cristian Pang, and I am running to be your Junior Class President. With this position I want to create an environment that is safe and open for everyone. As Covid is improving, we are slowly seeing what the Claremont Mckenna culture looks like. All of us have missed a huge chunk of our college experience and I believe that I can help make up many things that we have lost. One of the ways I will accomplish this is through organizing more amazing events for all of us to enjoy. Covid has put many barriers on many of our in-person events through capacity limits. One of my goals is to make these events more desirable to go to and accessible as I believe it would make the CMC environment more fun. The most important part about this position is hearing the opinion of you guys. If elected I would do everything in my power to try to implement the suggestions that I receive to make this a better place for all of us during these times. My name is Cristian Pang and I’m bringing sexy back to CMC. Sko Stags.', ' ', ' '],
    },

    {
      imageSource: ian,
      name: 'Ian Baime (2024 President)',
      candidateDescription: ['Hi all! I’m Ian Baime, I’m from Philly, and I’m running to be your class president. Here’s what I plan on doing:', 'Universalizing and Consolidating Access to School Resources','CMC offers an incredible amount of resources; QCL tutoring, counseling, and incredible career service prep are all provided to us without any additional payments. Accessing and learning about these resources, however, is not as easy. As class president, I would make it a top priority of mine to be organizing and presenting these resources on a new website designed solely to help you find what you’re looking for. If you’ve ever wondered “Hey, does CMC offer Python tutoring on Sunday nights?” or wanted to know when you can get your resume looked at but didn’t know where to start, I’m here to fix that problem. I want to create a single database where you can learn, for certain, what Claremont McKenna offers. All of our emails are cluttered. Let’s change that.','Building Community and Class Culture', 'Like all of you, I want to revitalize our class community. Zane’s midnight snacks have been a fantastic way to meet new people and spend time with other sophomores, but midnight assignments held many of us back from attending. I want to start small Junior-only pop-ups: free boba, coffee, and donuts during the in-betweens of going to and from classes would be a regular occurrence under my term. Amari set a fantastic example of this during her tenure as Junior class president last year. Her small events helped facilitate a bond amongst the class of ‘23; in the brief spaces as people ran between midterms, I watched this year’s Junior class take a moment and come together under the shared joy of apple cider. It’s an experience I would love to recreate in the class of ‘24.', 'Health and Wellness', 'As your class president, I would advocate for the expansion of CMC’s mental and physical health resources. Additional counseling, Plan-B available in-dorm, and the standardization of SDRC’s accommodations policies would all be top priorities for me. Claremont has a great existing infrastructure for maintaining student health, but we can make it better.', 'Thanks for giving me this opportunity. Remember to come out and vote!!!','',''],
    },

    {
      imageSource: wolfy,
      name: 'Wolfy Hutton (2024 President)',
      candidateDescription: ['Hi Class of 2024!  I\'m Wolfy Hutton and I\'m running to be your Junior Class President.  As we all know, our college careers were off to a rocky start, and in many ways we\'ve been denied the ability to engage with student life on campus in the ways that formerly defined CMC student culture.  Riding on the back of this new year (2022), I\'d like to look towards making our upcoming Junior Class into a more cohesive unit.  As former Student Body President of my small high school, I believe that I\'m well-suited to this role, and I look forward to learning from you more ways that I can improve my leadership.  I am grateful for any and every vote, and thank you once again Class of 2024!'],
    },
]

// // 2025
export const sophomore_candidate_data = [
    {
      imageSource: gio,
      name: 'Giovanni Pierre (2025 President)',
      candidateDescription: ['Hey CMC class of 2025!', 'My name is Gio Pierre (he/him) and I’m running to be your second-year class president. In my conversations with you all, one subject is consistently brought up: a lack of community among our class. Some of you are feeling isolated and are having trouble finding your people at CMC. I’m here to fix that. While I work behind the scenes on critical issues like divestment as well as diversity and inclusion, my overarching focus will be centered around community building.', 'We need to make the class of 2025 feel like one big family. I will plan a field day that’s just for us so we can have fun and get to know each other better. I’ll also meet with the 2025 class presidents from the other Claremont Colleges to plan a 5C class of 2025 party next year. I’ll send out weekly emails complete with helpful tips for self-care and academics, advertisements for smaller events that I’ll be hosting, and very corny jokes (my specialty). I’ll also be doing polls, Q&As, and suggestion boxes on Instagram because I value your input. I’ll be a smiling face around campus you can always come up to if you need someone to talk to or if you just want to hang out. I want you all to feel supported. Since parties aren’t for everyone, I’ll plan class mic nights, barbeques, and beach trips along with other non-party events. My cabinet will be a diverse group that will advise me on how best to advocate for all members of our class.', 'This past year, our class broke a CMC record with 81% voter turnout. Let’s break our own record and G.O. Vote 4 Gio on election day, Tuesday, March 1!', 'Peace and love <3', 'Gio', ' '],
    },

    {
      imageSource: bryan,
      name: 'Bryan Soh (2025 President)',
      candidateDescription: ['Hey guys! In case I haven’t had the pleasure of meeting you yet, I’m Bryan Soh (he/him), and I’m from sunny Singapore. Prior to college, I served in the Singaporean army as an officer and this past year, I have been serving on APASA’s executive board as Events Chair.', 'I want 2022 to be an even better year for us, and I won’t hesitate to get down to business to see our class’s vision come to fruition. Here is why I want to serve you as your SOHphomore class president:', '1) Improving 2025’s Community: Weekend kickbacks with boba & snacks, Netflix nights, karaoke evenings. Weekends are currently painfully underused, and there needs to be events suggested by you, for you.', 'Increasing Academic Support: Accessible study groups. Classes have been upping the ante, and I want that to foster more connections within our class, as well as connect us to more experienced upperclassmen.','Furthering D&I Initiatives: Inclusivity for under-represented groups. More socials for marginalized students to give you a safe space, and educational events to provide a platform within the wider CMC community. I want marginalized voices to be more than heard. I want them to matter.', 'More than your voice, I will be your hands and feet, working tirelessly to effect the changes you want to see in CMC. I also pledge to maintain open channels of communication to keep conversations flowing between the school and our class.','And most importantly, beyond this class president position, I just want to be a listening ear and a source of support for you guys. Say hi, or HMU at bsoh25@cmc.edu or on the ‘gram at @bryanjedidiah!'],
    },

    {
      imageSource: addy,
      name: 'Addison Reddinger (2025 President)',
      candidateDescription: ['Hello beautiful people! My name is Addison Reddinger (he/him) and I’m running to be your Sophomore Class President. I had the pleasure of serving as your First Year Class President and as a member of the Academic Affairs Committee last year. I’m beyond excited to hopefully continue to help better your lives at CMC!', 'It was an absolute joy seeing your smiling faces everyday and working to improve whatever I could. My cabinet and I accomplished a ton in our first year together and I wanted to use this space to be completely transparent about what we did.', 'Even with COVID restrictions and school rules changing daily, we were still able to:', 'Throw (and help/advertise) pregames with music, dancing, food, drinks, and more. (i.e. Monte Carlo Pregame), Contribute to school wide events helping any way we could. (i.e. Mistletoe Rock), Host our own events collaborating with other classes. (i.e. Prom), Put on a Worker’s Appreciation day in collaboration with the other presidents to thank our amazing staff, Provide funding and help organize non-drinking events in collaboration with the awesome students we have. (i.e. Super Smash Bros Tournaments), Worked for more mental health awareness on campus through informative emails thanks to the amazing Josh Nagra, Helped/advertised demographic specific socials. (BIPOC, LGBTQ+, International, First Gen)...', 'And so much more!!!', 'Though these things were so much fun and a pleasure to work on, the best part of my job was forming real connections with almost every CMC ‘25 student. I loved walking around with a smile asking everyone how their day is and if I can do anything to help.','I take this job seriously because I seriously care about you guys.', 'If you want to see more amazing results…','Don’t be misled, vote Addi Redd :)', ' ', ' ']
    },

    {
      imageSource: bianca,
      name: 'Bianca Rodriguez (2025 President)',
      candidateDescription: ['Hi! If we haven\'t had a chance to meet yet, my name is Bianca Rodriguez (she/her)! I\'m EXCITED to announce my candidacy for Class of 2025 President for our Sophomore year at CMC!', 'As class president, I will make a positive difference with my unique perspective as an East Coaster, tireless work ethic, and high-spirited personality!', 'Having played sports and served on student council, I have experience with listening to my peers to find compromises. At CMC, I am a member of Senate, the Working Group, and the Salvatori Center where I have worked with other members of the CMC community across all grades to plan fun events and implement new policies.', 'As President, I will contribute my experience and new ideas, as well as elect a diverse cabinet to guarantee everyone is heard and supported.', 'I routinely speak with classmates about wanted changes, which I will continue with an open door policy as President.', 'A few ideas to make this the best year: ', 'SOCIAL LIFE', '1) Off-campus group excursions to make the most of the GREAT area we live in outside of LA where tons to do.', '2) Social events with different classes where can share best practices and exchange resources as bond with one another', '3) Reward system to engage with CMC community', 'HEALTH SERVICES', '1) Improve mental health support', '2) Better access to health care', '3) Checking in on and supporting students when struggling', 'DIVERSITY & INCLUSION', 'Visit different towns known for different cultures and experience their traditions Celebrate different cultures and holidays on campus with a dance, presentations, meals Community service in different neighborhoods as get to know the communities and people while doing a good deed', 'I’m here FOR YOU!', 'I’ll email weekly debriefs to keep everyone in the loop, have an IG survey link (@_bianca_25), and hold open door hours. ', ' ']
    },
]